name: Green Swift
url: https://mattmaddux.github.io
description: Step by step Swift development for Linux, the Mac and iOS.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
