name: Green Swift
url: https://mattmaddux.github.io
description: Figuring Swift development out one step at a time.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
